[[redirects]]
  from = "/api/*"
  to = "https://223.130.129.40/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/proxy/*"
  to = "process.env.REACT_APP_SLACK_WEBHOOKS_URL/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200